### ISSUE TITLE
Content-Type:application/json with charset

### ISSUE THREAD

**Issue by nick2164** [lezhnev74/openapi-psr7-validator#46]
So i'm trying out your project, and i'm a huge fan.

Well i'm designing a restful api, and i'm testing my responses. 
While i was doing so, i found out that your body validator, doesn't like if the content-type is having a charset. This is kind of the standard of the framework that i'm using for the restapi.

As seen in the documentation from mozilla, there it's fully allowed to have both charset, and boundry as a parameter. [link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type)

### Symptoms
When the response is validated, it's not taken as json, even though application/json is in the content-type. Therefore, the response-body is not json decoded and taken as a string instead.

### Example
application/json; charset=UTF-8

### Suggested fix
/PSR7/Validators/Body.php:43 change '#^application/.*json$#' to '#^application/.*json#'
Now i know, this isn't bulletproof because it's not ending up with json, as the last word, but it allows a the charset string to be implementet.
I have though tested this and it now

**Comment by lezhnev74** [comment]
Hey! Yeah, I stumbled upon the same problem just recently and pushed a patch for that. It should be available since `0.15.0` version of the package. Can you check that you pull in the latest version?

This line here should trim all extra parameters from the header value:
https://github.com/lezhnev74/openapi-psr7-validator/blob/6d61b91ab2e91758aa04233d009d72bcb15e2dda/src/PSR7/Validators/BodyValidator.php#L55

**Comment by nick2164** [comment]
Headline: It's working! 

Well i found out that i was on the 0.13.8 version, and off course i should have updated and tested on the newest one, before committing an issue. Stupid me :P
